export const ITEM_CLASS_MAP: Record<string, string> = {
	Sceptres: 'weapon.sceptre',
	Wands: 'weapon.wand',
	Staves: 'weapon.staff',
	'One Hand Axes': 'weapon.oneaxe',
	'Two Hand Axes': 'weapon.twoaxe',
	'One Hand Maces': 'weapon.onemace',
	'Two Hand Maces': 'weapon.twomace',
	'One Hand Swords': 'weapon.onesword',
	'Two Hand Swords': 'weapon.twosword',
	'Thrusting One Hand Swords': 'weapon.sword.thrusting.1h',
	Bows: 'weapon.bow',
	Claws: 'weapon.claw',
	Quarterstaves: 'weapon.warstaff',
	Daggers: 'weapon.dagger',
	'Rune Daggers': 'weapon.runedagger',
	Warstaves: 'weapon.warstaff',
	Spears: 'weapon.spear',
	Flails: 'weapon.flail',
	Crossbows: 'weapon.crossbow',
	Traps: 'weapon.trap',
	Axes: 'weapon.axe',
	Swords: 'weapon.sword',
	'Body Armours': 'armour.chest',
	Boots: 'armour.boots',
	Gloves: 'armour.gloves',
	Helmets: 'armour.helmet',
	Shields: 'armour.shield',
	Bucklers: 'armour.buckler',
	Quivers: 'armour.quiver',
	Amulets: 'accessory.amulet',
	Rings: 'accessory.ring',
	Belts: 'accessory.belt',
	Jewels: 'jewel',
	'Life Flasks': 'flask.life',
	'Mana Flasks': 'flask.mana'
};
